### PR TITLE
[ADD] Forward Port

### PR DESCRIPTION
**Pull request by hbto**
-

This PR is the port forward of
https://github.com/OCA/account-financial-tools/pull/1057 which is based
on https://github.com/odoo/odoo/pull/44444

Dependency
-

This PR depends on Odoo merging https://github.com/odoo/odoo/pull/61105

### CODE REVIEW

**Comment by hbto** [comment]
@luisg123v Could you please review

@ljpachec after Luis review and endorse you could be able to merge.

@luisg123v This is being carried in task 39503.

Regards.

**Review by luisg123v — CHANGES_REQUESTED** [review]
Hi @hbto,

I don't get why you're copying the module here.

AFAIK, you should use the repo account-financial-tools (as a submodule).

Even if you'd need to copy the module, you should copy it [here](https://git.vauxoo.com/vauxoo/urbvan/tree/13.0)

BTW, for adding any new module, the following should be done:
- Added there, either by its repo or (in some cases) copying it)
- Added to the module's manifest
- Increased the module version, so it's automatically installed when deployed into production.

**Comment by hbto** [comment]
@luisg123v 

> I don't get why you're copying the module here.
> 
> AFAIK, you should use the repo account-financial-tools (as a submodule).

I haven't used AFT because that version is 13.0 which is still in migration and not merged not the PR in odoo on which it depends nor the PR in OCA.


> Even if you'd need to copy the module, you should copy it [here](https://git.vauxoo.com/vauxoo/urbvan/tree/13.0)

I wasn't aware of it.

thanks I will take care of it that way.

Regards.

**Comment by hbto** [comment]
@hugho-ad Could you please merge after @luisg123v Review.


Regards.

**Review by luisg123v — APPROVED** [review]

**Pull request merged**
